export const PERMISSION_CODE = {
  VIEW_ALL_MEMBER_EVENT: 'VIEW_ALL_MEMBER_EVENT',
  VIEW_ALL_PERMISSION: 'VIEW_ALL_PERMISSION',
  ADD_OR_UPDATE_PERMISSION_IN_ROLE: 'ADD_OR_UPDATE_PERMISSION_IN_ROLE',
};
export const PERMISSION_PATH = {
  PERMISSION: 'permissions',
  MEMBER_EVENT: 'member-events',
};
