export enum PermissionCode {
  SCAN_TICKET = 'SCAN_TICKET',
  VIEW_CHECKIN_REPORT = 'VIEW_CHECKIN_REPORT',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  MANAGE_SEAT_MAP = 'MANAGE_SEAT_MAP',
  VIEW_ORDERS = 'VIEW_ORDERS',
  SEND_CUSTOMER_EMAIL = 'SEND_CUSTOMER_EMAIL',
  EXPORT_ORDER_REPORT = 'EXPORT_ORDER_REPORT',
  VIEW_REVENUE = 'VIEW_REVENUE',
  VIEW_MARKETING_ANALYTICS = 'VIEW_MARKETING_ANALYTICS',
  MANAGE_VOUCHERS = 'MANAGE_VOUCHERS',
  EDIT_EVENT = 'EDIT_EVENT',
}
